Added: Resend OTP feature
beyondszine/dareyou pull request #7
Opened 2023-05-06 11:03 UTC by rohit3463

2023-05-09 03:56 UTC, beyondszine requested changes

2023-05-09 04:43 UTC, rohit3463 commented on lib/screens/login/bloc/login_bloc.dart
> +        completer.complete(true);
Yes, will create a authentication module for this and use that here

2023-05-09 04:44 UTC, rohit3463 commented on lib/screens/login/ui/login.dart
> +            print("Navigating to verification screen!!");
```suggestion
            debugPrint("Navigating to verification screen!!");
```

2023-05-09 04:46 UTC, rohit3463 commented on lib/screens/verify/ui/verify_otp.dart
> +            ScaffoldMessenger.of(context).showSnackBar(
`??` should do that same, in case the `authExeption` in null it will show `Something went wrong.`

2023-05-09 04:48 UTC, rohit3463 commented on lib/screens/verify/bloc/verify_bloc.dart
Yes, makes sense

2023-05-09 04:49 UTC, rohit3463 commented on lib/main.dart
But firebase must be initialized prior to runApp, will make changes for that as well

2023-05-09 08:14 UTC, beyondszine submitted a review, later dismissed

2023-05-10 03:01 UTC, beyondszine submitted a review, later dismissed

2023-05-10 06:37 UTC, beyondszine approved these changes

2023-05-10 06:37 UTC, merged